update integration test  on github actions

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1696,15 +1696,15 @@ jobs:
             -d '{"numbers":[1,2,3,4,5],"luckyNumber":6, "drawDate":"2025-03-12"}' \
             -b cookies.txt
 
-#       # 🔄 Scraping des résultats FDJ via le service Spring Boot
-#       - name: 🔄 Run Loto Scraper
-#         run: |
-#           curl -X GET "http://localhost:8082/api/loto/scrape"
+      # 🔄 Scraping des résultats FDJ via le service Spring Boot
+      - name: 🔄 Run Loto Scraper
+        run: |
+          curl -X GET "http://localhost:8082/api/loto/scrape"
 
-#       # 🏆 Calcul automatique des gains via l’API
-#       - name: 🏆 Calculate Ticket Winnings
-#         run: |
-#           curl -X GET "http://localhost:8082/api/gains/calculate"
+      # 🏆 Calcul automatique des gains via l’API
+      - name: 🏆 Calculate Ticket Winnings
+        run: |
+          curl -X GET "http://localhost:8082/api/gains/calculate"
 
 #       # 📅 Vérifier les tirages disponibles
 #       - name: 🔍 Get Available Draw Dates
@@ -1776,25 +1776,25 @@ jobs:
       #       exit 1
       #     fi
 
-      - name: 🔄 Run Loto Scraper
-        run: |
-          response=$(curl -s -o /dev/null -w "%{http_code}" -X GET "http://localhost:8082/api/loto/scrape")
-          if [ "$response" -eq 200 ]; then
-            echo "✅ Scraping successfully started!"
-          else
-            echo "❌ Scraping failed. HTTP Code: $response"
-            exit 1
-          fi
+      # - name: 🔄 Run Loto Scraper
+      #   run: |
+      #     response=$(curl -s -o /dev/null -w "%{http_code}" -X GET "http://localhost:8082/api/loto/scrape")
+      #     if [ "$response" -eq 200 ]; then
+      #       echo "✅ Scraping successfully started!"
+      #     else
+      #       echo "❌ Scraping failed. HTTP Code: $response"
+      #       exit 1
+      #     fi
 
-      - name: 🏆 Calculate Ticket Winnings
-        run: |
-          response=$(curl -s -o /dev/null -w "%{http_code}" -X GET "http://localhost:8082/api/gains/calculate")
-          if [ "$response" -eq 200 ]; then
-            echo "✅ Ticket winnings calculated!"
-          else
-            echo "❌ Ticket winnings calculation failed. HTTP Code: $response"
-            exit 1
-          fi
+      # - name: 🏆 Calculate Ticket Winnings
+      #   run: |
+      #     response=$(curl -s -o /dev/null -w "%{http_code}" -X GET "http://localhost:8082/api/gains/calculate")
+      #     if [ "$response" -eq 200 ]; then
+      #       echo "✅ Ticket winnings calculated!"
+      #     else
+      #       echo "❌ Ticket winnings calculation failed. HTTP Code: $response"
+      #       exit 1
+      #     fi
 
       - name: 🔍 Get Available Draw Dates
         run: |
